### ISSUE TITLE
Config File Location

### ISSUE THREAD

**Issue by StefanGreve** [StefanGreve/timetravel#1]
Currently the script only works when `pwd` is set to `src`. Find a way to work around this?

**Comment by briantoe** [comment]
You could maybe write a simple bash script that executes a cd into the src folder, executes the code, and then cd back out?

**Comment by StefanGreve** [comment]
Yes this could also work. But I think, especially on Unix systems, that is is more appropriate to move setting files to `etc/timetravel` because that's where I would be looking for first. Windows doesn't really have a default path for configuration files because users a accustomed to change settings through a GUI, although I used `AppData\Roaming` in some of my .NET projects before.

**Comment by StefanGreve** [comment]
Last commit should have fixed this issue, at least on my PC it now works everywhere~
